version: "3"
services:
  web:
    image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
    restart: always
    container_name: dk-gitlab-web
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  # runner:
  #   build: runner
  #   container_name: dk-gitlab-runner
  #   restart: always
  #   image: ci-gitlab-runner:latest
  #   environment:
  #     - RUNNER_HOME=runner
  #     - CI_SERVER_URL=http://gitlab.example.com:8929/ci
  #     - REGISTRATION_TOKEN=xxxx
  #     - RUNNER_EXECUTOR=docker
  #     - DOCKER_IMAGE=alpine:latest
  #     - DOCKER_PRIVILEGED=true
  #   volumes:
  #     - ./$RUNNER_HOME/config:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock
    

